Fix testcode
kuninari/rspec_app_exam pull request #1
Opened 2020-08-10 03:21 UTC by kuninari

2020-08-11 02:29 UTC, yuji91 requested changes

2020-08-11 02:29 UTC, yuji91 commented on spec/factories/tasks.rb
> +        status { 2 }
2だと何を意味するのか分からないので、Symbolで記載して伝わるようにしましょう！
`マジックナンバー`で調べてみてください。
```suggestion
        status { :done }
```

2020-08-11 02:29 UTC, yuji91 commented on spec/system/task_spec.rb
> +require 'byebug'
requireしなくても、byebug自体をtest環境に含めてbundle installしていれば使えるかと思います。

2020-08-11 02:29 UTC, yuji91 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(handle)
1行で書けるのでこっちの方が良いかもですね。
```suggestion
        switch_to_window(windows.last)
```

2020-08-11 02:29 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
解答例のPRでも言及していますが、strftimeで直接書き換えると、View側の表示の仕様が変わるとテストが失敗します。
Viewで使用しているメソッドを使うようにしましょう。

2020-08-11 04:22 UTC, kuninari commented on spec/system/task_spec.rb
> +require 'byebug'
dd81133 で修正しました。

2020-08-11 04:22 UTC, kuninari commented on spec/factories/tasks.rb
> +        status { 2 }
d4bae1d で修正しました。

2020-08-11 04:23 UTC, kuninari commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(handle)
0fa8abb で修正しました。

2020-08-11 04:25 UTC, kuninari commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
3be2d20 で修正しました。
rails_helper.rbにconfig.include ApplicationHelperの記述をしたのですが、この通りで大丈夫でしょうか？

2020-08-11 04:30 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
そのやり方で大丈夫です！

2020-08-11 04:31 UTC, yuji91 approved these changes
良いかと思います！

ここで学んだことをtimesやブログでアウトプットしてもらえると、良い復習になるかと思いますm(_ _)m

2020-08-11 08:25 UTC, merged

2020-08-13 09:10 UTC, yuji91 reviewed
こちらもうマージ済なので、修正しなくても内容の確認だけで大丈夫です！🙆

2020-08-13 09:10 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:done_task) { create(:task, :done_task, project_id: project.id) }
FactoryBotでassociationを定義すると、project_idを指定しなくて済むので、記載を減らせますね。
```
let(:task) { create(:task) }
let(:done_task) { create(:task, :done_task) }
```